In [6]:
a=100000
type(a)


int

In [7]:
a.bit_length()

17

In [8]:
1.0/4

0.25

In [9]:
a= "this is a string"


In [10]:
a.capitalize()

'This is a string'

In [11]:
a.split()

['this', 'is', 'a', 'string']

In [12]:
import numpy
def append_if_not_exists(arr, x):
    if x not in arr:
        arr.append(x)

def some_useless_slow_function():
    arr = list()
    for i in range(10000):
        x = numpy.random.randint(0, 10000)
        append_if_not_exists(arr, x)
        

In [14]:
Writing test.py

SyntaxError: invalid syntax (<ipython-input-14-2bce5a3db05f>, line 1)

In [15]:
Writing pythoncode.py

SyntaxError: invalid syntax (<ipython-input-15-66dd9e607ebe>, line 1)

In [17]:
a.find("string")

10

In [18]:
a.count("string")

1

In [19]:
l=[1,2.5,'amin']
l

[1, 2.5, 'amin']

In [21]:
l.append([2,3])
l

[1, 2.5, 'amin', [2, 3]]

In [23]:
l.extend([5])
l

[1, 2.5, 'amin', [2, 3], 5]

In [24]:
l=[2.5,6,3,12,3.4,2]
l


[2.5, 6, 3, 12, 3.4, 2]

In [27]:
for element in l[2:5]:
    print element ** 2

9
144
11.56


In [26]:
l[2:5]

[3, 12, 3.4]

In [28]:
s = 'amin'
n =52.5

In [29]:
print (s)

amin


In [30]:
print(n,s)

(52.5, 'amin')


In [33]:
print ('%s %d' %(s,n))

amin 52


In [34]:
def even (x):
    return x%2==0
map(even,range(10))

[True, False, True, False, True, False, True, False, True, False]

In [36]:
def cumsum(l):
    total =0
    for element in l:
        total += element
    return total
cumsum(range(10))

45

In [37]:
l


[2.5, 6, 3, 12, 3.4, 2]

In [38]:
l.std()

AttributeError: 'list' object has no attribute 'std'

In [39]:
import numpy as np
l2 = np.array(l)
l

[2.5, 6, 3, 12, 3.4, 2]

In [40]:
l2

array([  2.5,   6. ,   3. ,  12. ,   3.4,   2. ])

In [41]:
l2.std()

3.4546667309918941

In [42]:
import random
I = 5000


In [43]:
%time M = [[random.gauss(0,1) for i in range(I)] for i in range(I)]

CPU times: user 23.4 s, sys: 442 ms, total: 23.9 s
Wall time: 24 s


In [44]:
M[0,1]

TypeError: list indices must be integers, not tuple

In [45]:
M[0][1]

-0.3197221825694993

In [46]:
%time mat = np.random.standard_normal((I, I))

CPU times: user 824 ms, sys: 84.2 ms, total: 909 ms
Wall time: 925 ms


In [49]:
np.random.standard_normal((2,2))

array([[ 0.10945936, -0.17254853],
       [-0.65891445, -1.25196374]])

In [50]:
r = np.random.standard_normal((4,3))
r

array([[-0.92965083, -0.11427175, -1.25928083],
       [-0.05296573,  1.02785432,  1.18895361],
       [ 0.18053579, -0.10984386,  0.12884105],
       [-1.47095761, -0.12892746, -0.1745402 ]])

In [51]:
s = np.random.standard_normal(3)
s

array([-0.51243257,  0.17960829,  1.43826359])

In [52]:
r + s

array([[-1.4420834 ,  0.06533653,  0.17898276],
       [-0.5653983 ,  1.20746261,  2.62721721],
       [-0.33189679,  0.06976443,  1.56710464],
       [-1.98339018,  0.05068083,  1.26372339]])